import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
	title: "GPTGenius",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className="">{children}</body>
			</html>
		</ClerkProvider>
	);
}
